version: "3.4" 
services: 
  untappd.kolosbot: 
    build: 
      context: "."
      dockerfile: src/Untappd.KolosBot/Untappd.KolosBot/Dockerfile
    environment: 
      - "BOT_TOKEN=${BOT_TOKEN}"
    image: aspnetapp