version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout 
     
     - run:
        name: Install Docker Compose
        command: |
            curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

     # build image
     - run: |         
         docker info
         docker-compose -f src/Untappd.KolosBot/docker-compose.yml -e "BOT_TOKEN=$BOT_TOKEN" up -d
     # deploy the image
     - run: |         
         docker login --username=$HEROKU_USERNAME --password=$HEROKU_API_KEY registry.heroku.com
         docker tag aspnetapp registry.heroku.com/$HEROKU_APP_NAME/web
         docker push registry.heroku.com/$HEROKU_APP_NAME/web                
         curl https://cli-assets.heroku.com/install.sh | sh
         heroku container:release web -a $HEROKU_APP_NAME